# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_install:
      - git update-index --assume-unchanged docs/conf.py docs/rtd_environment.yaml

conda:
  environment: docs/rtd_environment.yaml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: []
